## Printegrate:
Integrating 3d printing with off-the-shelf parts. This page is for examples that integrate 3D printing with OTS parts.  I'll call it printegrating, to set apart these designs from all the world's 3D printed parts.

**Reducer**
An example part for reducing a hole to host a fastener.  One example is to outfit concentric shafts in a steel outlet box to achieve nicely-aligned axes in a gearbox.   The second example offers a location for M8 fastener in a large 14mm hole of a disc brake.  Utility aside, it's a lesson in compliant mechanisms, gaining concentricity, bearing loads on a 3D printed part, retaining a steel nut with friction.  Jump to grabCAD post:[reducer model](https://grabcad.com/library/reducer-115)
- ![grabcad image, reducer1](https://d2t1xqejof9utc.cloudfront.net/screenshots/pics/bf1a57fef2f3299b50b64ec13ba34092/original.jpg)
- ![grabcad image, reducer in disc brake](https://d2t1xqejof9utc.cloudfront.net/screenshots/pics/7da5515543f983b4f8067bdb2cd499ce/original.jpg)
- ![linked image, reducer section](https://d2t1xqejof9utc.cloudfront.net/screenshots/pics/37432ac2405823741c98dce59bbf3fd1/original.JPG)

**Hinge**
Printable and print-in-place design for a hinge for 2020 extrusions. Tap M6 threads in a 2020 extrusion or mount to the side of the extrusion with M5x10mm fastener as usual.  The hinge pin uses 1/4 or 6mm stock such as HDPE tubing, or a simple steel cotter pin. The hinge model is highly parametric and many variations are possible. Note the limits on the rotation built into the model.  The rotation stops at +90 or -90 for the template parts.  Important templates include hingeEnd for extrusion ends, hinge30 for 3030 extrusions, and hingeRod for joining 10mm rebar to the assembly.  Model for [hingeEnd here](https://grabcad.com/library/hinge_end-1), model for [hingeRod here](https://grabcad.com/library/hingerod-1) and model for [pivotBeam here](https://grabcad.com/library/pivotbeam-1) which features dual-rotation for 180 degrees while maintaining strength.
- ![grabcad image, hinge end](https://d2t1xqejof9utc.cloudfront.net/screenshots/pics/f669f96e0e3e77caca9a3cbfcb0a2fa9/original.jpg)
- ![grabcad image, hinge](https://d2t1xqejof9utc.cloudfront.net/screenshots/pics/7da5515543f983b4f8067bdb2cd499ce/original.jpg)

**PivotBeam**
this model predates the hinge designs for 2020 extrusion, and uses a 3/8 pin instead of the smaller 1/4 pin.  Again, the common LDPE tubing for water distribution fits in this design.
- ![linked image, pivotBeam](https://d2t1xqejof9utc.cloudfront.net/screenshots/pics/429120eb8b0ff14aba73812c9da91e6d/original.JPG)
- ![linked pivotbeam photo](https://d2t1xqejof9utc.cloudfront.net/screenshots/pics/664899e789a93b41ac4b7d161640d058/original.jpg)
- ![linked pivotbeam photo2](https://d2t1xqejof9utc.cloudfront.net/screenshots/pics/a3ca020667c495bd0a8325c0842493a8/original.jpg)

**Collar**
This is a simple concept of gaining a concentric mate of round stock and unistrut steel channel. model for [unistrut collar here](https://grabcad.com/library/collar-14)
